spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      location: uploads
  security:
    user:
      name: chirag
      password: chirag
  mail:
    host: localhost
    port: '1025'
    username: admin@mailhog.com
    password: secret
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jmx:
    enabled: false

management:
  health:
    mail:
      # TODO Disable once mail is up and running
      enabled: false
  endpoints:
    web:
      exposure:
        include: 'health,info'
